SELECT MAILCLIENT
FROM TIRAGE NATURAL JOIN IMPRESSION NATURAL JOIN PHOTOTIRAGE NATURAL JOIN PHOTO NATURAL JOIN FICHIERIMAGE;

SELECT MAILCLIENT
FROM AGENDA NATURAL JOIN IMPRESSION NATURAL JOIN PHOTOAGENDA NATURAL JOIN PHOTO NATURAL JOIN FICHIERIMAGE;

SELECT MAILCLIENT
FROM CALENDRIER NATURAL JOIN IMPRESSION NATURAL JOIN PHOTOCALENDRIER NATURAL JOIN PHOTO NATURAL JOIN FICHIERIMAGE;

SELECT MAILCLIENT
FROM ALBUM NATURAL JOIN IMPRESSION NATURAL JOIN PHOTOALBUM NATURAL JOIN PHOTO NATURAL JOIN FICHIERIMAGE;

SELECT MAILCLIENT
FROM CADRE NATURAL JOIN IMPRESSION NATURAL JOIN PHOTOCADRE NATURAL JOIN PHOTO NATURAL JOIN FICHIERIMAGE;
