/*
VÉRIFIER QUE QUAND LA COMMANDE CRÉÉE PEUT L'ÊTRE
SURVEILLER LA TABLE COMMANDE
ARTICLE( NUMCOMMANDE, IDARTICLE , NUMIMPRESSION)


CREATE OR REPLACE TRIGGER CHECK_COMMANDE_SEMAINES
AFTER INSERT OR UPDATE ON COMMANDE
DECLARE 
   NB_COMMANDE INTEGER;
   STOCK_COMMANDE INTEGER;
BEGIN 

SELECT QUANTITE
FROM ARTICLE NATURAL JOIN COMMANDE NATURAL JOIN IMPRESSION NATURAL JOIN JOURS


SELECT QUANTITESTOCK INTO STOCK_COMMANDE
FROM STOCK 
WHERE TYPE_IMPRESSION='SEMAINES';
*/

/*
UNE COMMANDE QUI PASSE A OK DOIT AVOIR TOUTES SES IMPRESSIONS OK
*/

/*
VERIFIER QUE L'ARTICLE PEUT PASSER DE 0 À 1, ASSEZ DE STOCK
impression ou article
*/
CREATE OR REPLACE TRIGGER IMPRESSION_SEMAINES
BEFORE INSERT OR UPDATE ON IMPRESSION
DECLARE
   STOCK_SEMAINES INTEGER;
BEGIN 

   SELECT QUANTITESTOCK INTO STOCK_SEMAINES
   FROM STOCK 
   WHERE TYPE_IMPRESSION='SEMAINES';

   IF (STOCK_SEMAINES < 10 and :new.) THEN
      RAISE_APPLICATION_ERROR(-20001, 'IMPRESSION PAS POSSIBLE CAR MANQUE DE STOCK');
   end if;
end;
/
